blank_issues_enabled: false
contact_links:
  - name: "\U0001F680 Feature Request"
    url: https://github.com/orgs/alovajs/discussions/new?category=feature-request
    about: Suggest new features for consideration.

  - name: Questions & Discussions
    url: https://github.com/orgs/alovajs/discussions/new?category=q-a
    about: Use GitHub discussions for your questions and discussions.

  - name: Official Documentation
    url: https://alova.js.org
    about: Before submitting a bug, you can first look for a solution through the official documentation

  - name: Discord Chat
    url: https://discord.gg/S47QGJgkVb
    about: Ask questions and discuss with other users in real time.

  - name: 加入微信群
    url: https://alova.js.org/img/wechat_qrcode.jpg
    about: 在微信群聊中和我们交流.
